ARA-Trans/iAM

BridgeCareApp/VuejsApp/src/components/investment-editor/InvestmentEditor.vue, BridgeCareApp/VuejsApp/src/components/investment-editor/investment-editor-dialogs/CreateInvestmentStrategyDialog.vue, BridgeCareApp/VuejsApp/src/components/investment-editor/investment-editor-dialogs/EditBudgetsDialog.vue, BridgeCareApp/VuejsApp/src/components/investment-editor/investment-editor-dialogs/SetRangeForAddingBudgetYearsDialog.vue, BridgeCareApp/VuejsApp/src/services/investment-editor.service.ts, BridgeCareApp/VuejsApp/src/shared/models/dialogs/create-investment-strategy-dialog-result.ts, BridgeCareApp/VuejsApp/src/shared/models/dialogs/edit-budgets-dialog-result.ts, BridgeCareApp/VuejsApp/src/shared/models/dialogs/investment-editor-dialogs/create-investment-strategy-dialog-data.ts, BridgeCareApp/VuejsApp/src/shared/models/dialogs/investment-editor-dialogs/edit-budgets-dialog-data.ts, BridgeCareApp/VuejsApp/src/shared/models/iAM/investment.ts, BridgeCareApp/VuejsApp/src/shared/utils/getter-utils.ts, BridgeCareApp/VuejsApp/src/shared/utils/mock-data.ts, BridgeCareApp/VuejsApp/src/shared/utils/sorter.ts, BridgeCareApp/VuejsApp/src/store-modules/investment-editor.module.ts
-modified investment editor ui so that the inflation & discount rates show up beneath the selected investment strategy name
-modified CreateInvestmentStrategyDialog by adding fields for the inflration & discount rates and also having these fields pre-populated when electing to create as a new library from a selected library
-modified EditBudgetsDialog by adding a card title and making the fab buttons smaller
-added an isNew property to the EditBudgetsDialogGridData
-separated saveInvestmentStrategyToLibrary service itno createInvestmentStrategy & updateInvestmentStrategy services
-refactored InvestmentStrategy & InvestmentStrategyBudgetYear models for more flexibility (updated mock data to match changes)
-simplified investment-editor.module to adding create/update functionality for …
=> Feature/127: Investment Editor UI Refactor

BridgeCareApp/BridgeCare/DataAccessLayer/PerformanceLibrary.cs, BridgeCareApp/VuejsApp/src/components/performance-editor/PerformanceEditor.vue, BridgeCareApp/VuejsApp/src/store-modules/investment-editor.module.ts
-fixed UI by adding the appropiate payload data instead of the incorrectly used selected library data that was not being modified with the selected scenario id
-adjusted the backend api to save data where appropriate (e.g., deleting performance records before creating new ones to avoid foreign key violations)
=> Bug/269: SavePerformanceLibrary UI/API Fixes

BridgeCareApp/BridgeCare/BridgeCare.csproj, BridgeCareApp/BridgeCare/Controllers/ValidationController.cs, BridgeCareApp/BridgeCare/DataAccessLayer/CommittedDAL.cs, BridgeCareApp/BridgeCare/Interfaces/ICommitted.cs, BridgeCareApp/BridgeCare/Models/ValidateCriteriaModel.cs, BridgeCareApp/BridgeCare/Services/CommittedProjects.cs, BridgeCareApp/BridgeCareNodeApp/config/express.js, BridgeCareApp/VuejsApp/src/services/criteria-editor.service.ts, BridgeCareApp/VuejsApp/src/shared/modals/CriteriaEditorDialog.vue, BridgeCareApp/VuejsApp/src/shared/modals/EquationEditorDialog.vue, BridgeCareApp/VuejsApp/src/shared/models/iAM/criteria-validation.ts
-added a criteria-editor.service.ts to hook into validation api
-added check/submit logic to criteria editor
-updated validation api to return an OK response but with the validation error if a criteria is invalid to prevent triggering the axios error interceptor
-fixed committed entity references
-increased size of allowed payloads for nodejs
=> Feature/317: Criteria Editor Validation

BridgeCareApp/BridgeCare/DataAccessLayer/AttributesByYearDAL.cs, BridgeCareApp/BridgeCare/Models/AttributeByYearModel.cs
--renamed selectStatement to query, added 2nd parameter (SqlParameter, sectionIdParameter)
--added SqlCommand functionality; DataTable Load() function uses SqlDataReader returned by SqlCommand ExecuteReader() to create a DataTable
-modified the query strings in GetProjectedAttributes & GeneralAttributeValueQuery with parameters and added a sectionIdParameter SqlParameter for each
-coding best practice (movied AttributeByYearModel properties to top of class definition
=> Bug/346: Parameterize Raw Queries => AttributeByYearDAL.cs

BridgeCareApp/BridgeCare/DataAccessLayer/RemainingLifeLimitDAL.cs
-moved a logic block that saved new remaining life limit data if there was no matching data already found to be existing (caused new data not to be saved when there was no existing data found to begin with)
=> Bug/413: Remaining Life Limit Save Data to UI Fix

BridgeCareApp/BridgeCare/DataAccessLayer/SimulationDAL.cs, BridgeCareApp/BridgeCare/DataAccessLayer/SummaryReport/BridgeDataDAL.cs
-appended '_0' to all raw queries querying on dynamic simulation tables
-fixed the GetSummaryReportMissingAttributes function not returning the found columns to match against the required columns
-fixed the GetDynamicColumns function not properly concatenating all dynamic columns pertaining to each simulation year
=> Bug #455: Summary Report Simulation Variables

BridgeCareApp/BridgeCare/DataAccessLayer/SimulationDAL.cs, BridgeCareApp/BridgeCareNodeApp/controllers/scenarioController.js, BridgeCareApp/BridgeCareNodeApp/routes/scenarioRouters.js, BridgeCareApp/VuejsApp/src/store-modules/scenario.module.ts
-modified nodejs scenario delete function to use the mongo db deleteOne collection method and return the results to eliminate the axios http request hang up
-modified API scenario delete functionality to use a 'using' statement to ensure correct use of disposable objects
-renamed nodejs scenario routes from 'routes' to 'scenarioRoutes'
-updated deleteScenario and scenario socket module actions: use payload provided identifiers in deleteScenario action; added more user friendly info message when delete occurs from another source
=> 473: Fix MongoDB Scenario Delete Functionality

BridgeCareApp/BridgeCareNodeApp/app.js, BridgeCareApp/VuejsApp/src/components/investment-editor/InvestmentEditor.vue, BridgeCareApp/VuejsApp/src/shared/utils/currency-formatter.ts
-added a formatAsCurrency utility function that will format any number|string values that are numbers (isNaN=false) as us dollars
-updated investment editor so all budget amounts use the formatAsCurrency utility for the output
=> vnext/447: Currency Formatting

BridgeCareApp/VuejsApp/src/components/priority-editor/PriorityEditor.vue
The fixed-header class prevents the Priorities editor table from expanding to make room for large numbers of Budgets
=> Allow data table columns to have varied width

BridgeCareApp/VuejsApp/src/App.vue, BridgeCareApp/VuejsApp/src/components/Authentication.vue, BridgeCareApp/VuejsApp/src/components/AuthenticationStart.vue, BridgeCareApp/VuejsApp/src/components/LandingPage.vue, BridgeCareApp/VuejsApp/src/router.ts, BridgeCareApp/VuejsApp/src/shared/models/iAM/authentication.ts, BridgeCareApp/VuejsApp/src/shared/models/iAM/user-information.ts, BridgeCareApp/VuejsApp/src/shared/utils/authorization-header.ts, BridgeCareApp/VuejsApp/src/store-modules/authentication.module.ts
-updated authentication module with the localStorage functionality and reducing state to just an authenticated flag and username
-added an onLogout function that will redirect users to a landing page (need to flesh this out for production)
-added models for user tokens and user info
-updated authorization header to pull the bearer from local storage
=> vnext/514: Store user auth info in client localStorage

BridgeCareApp/VuejsApp/src/components/scenarios/Scenarios.vue
After PR #537, there is no "loginFailed" in the vuex store.
=> Update Scenarios page to use new authentication store data

BridgeCareApp/VuejsApp/src/App.vue, BridgeCareApp/VuejsApp/src/store-modules/authentication.module.ts
- Users do not need to log in for each tab or window they open
- Users do not need to log in again if they have not logged out in the last half hour
- Login persists through browser refresh
- When a user logs in or out on one tab, all other tabs will update to reflect this change within 30 seconds
=> vnext/530 - On loading, check local storage for previous login

BridgeCareApp/VuejsApp/src/components/LandingPage.vue
If reached through a redirect, the *penndot.gov/iAM/ page fails to set the cookie until the page is refreshed.
=> vnext/522-fix - Refresh landing page once on load

BridgeCareApp/BridgeCare/Controllers/SimulationController.cs
- Only allow Administrators and DBEngineers to run simulations
=> vnext/554 - Restrict access to RunSimulation endpoint

BridgeCareApp/VuejsApp/.env.development, BridgeCareApp/VuejsApp/.env.production, BridgeCareApp/VuejsApp/.env.staging, BridgeCareApp/VuejsApp/src/main.ts, BridgeCareApp/VuejsApp/src/store-modules/authentication.module.ts
- Socket.io was stripping the path away from the URI it was given. It must be given the path explicitly in its configuration.
- Upon refreshing the page, there was a race condition between the tasks of refreshing the old tokens and using the new tokens to get user info. These now take place sequentially.
=> vnext/554 - Socket.io and refresh

.gitignore, Deployment/configurations/bams/.env.production, Deployment/configurations/bams/authorizationConfig.js, Deployment/configurations/bams/oidc-config.ts, Deployment/configurations/bamsdev/.env.production, Deployment/configurations/bamsdev/oidc-config.ts, Deployment/configurations/bamssyst/.env.production, Deployment/configurations/bamssyst/oidc-config.ts, Deployment/configurations/iam-deploy/oidc-config.ts, Deployment/deploy.ps1, Deployment/readme.txt
- Automates the full app configuration process and vue app build process
- esec.config files must be manually added, since client_id cannot be stored on a public repo
If you use this script and then switch to a branch that has not yet had these changes merged into it, you will need to update that branch's .gitignore to avoid uploading your deployment packages to the repo.
=> vnext/576 - Add deployment script to repo

BridgeCareApp/VuejsApp/src/shared/modals/CriteriaEditorDialog.vue
-fixed bug where incorrect conjunction was being used when parsing a criteria string that has a logical operator
=> vnext/644: Criteria Editor Selected Conjunction Fix

BridgeCareApp/VuejsApp/vue.config.js
Change webpack's filename delimiter to '_' from '~'
=> vnext/659 - Webpack delimiter

BridgeCareApp/VuejsApp/src/shared/utils/criteria-editor-parsers.ts
The criteria that isn't loading properly on bamssyst contains doubled spaces and has invalid spaces in between operators and their operands.
The parser now trims away such spaces before attempting to parse the criteria.
=> vnext/681 - Remove invalid spaces before parsing criteria

BridgeCareApp/VuejsApp/src/components/cash-flow-editor/CashFlowEditor.vue, BridgeCareApp/VuejsApp/src/shared/models/iAM/cash-flow.ts, BridgeCareApp/VuejsApp/src/shared/utils/has-value-util.ts
-updated hasValue helper function so that it only checks against null, undefined, empty string, and empty array values to determine if an object or property has a value (0s will be considered a value)
-updated SplitTreatmentLimit.amount property to allow nulls
-updated CashFlowEditor to allow empty values for SplitTreatmentLimit amounts
=> #691: Add ability to have a blank amount for cash flow amount

BridgeCareApp/VuejsApp/src/components/investment-editor/InvestmentEditor.vue
- When investment data is missing, it no longer causes an error; instead, default values ($0) are used
- "Year 0" is no longer created
=> vnext/742 - Year 0 investments

BridgeCareApp/VuejsApp/src/components/investment-editor/InvestmentEditor.vue, BridgeCareApp/VuejsApp/src/shared/modals/EditBudgetsDialog.vue
-removed saveIntermittentCriteriaDrivenBudgetAction property & and action dispatch from EditBudgetsDialog component (no longer exists)
-removed unused properties budgetCriteriaHeaders & currencyInputConfig from InvestmentEditor component
-updated selectedInvestmentLibrary modification code for specified budgetYear inside onEditBudgetYearAmount function
-updated selectedInvestmentLibrary modification code inside onApplyToScenario function
=> vnext/771: (bugfix) Investment editor not saving after editing budget criteria

BridgeCareApp/BridgeCare/Controllers/SimulationController.cs, BridgeCareApp/BridgeCare/DataAccessLayer/SimulationDAL.cs, BridgeCareApp/BridgeCare/Interfaces/ISimulation.cs
-added BridgeCareContext as a parameter to 'RunSimulation' function
-added select for simulation inside 'RunSimulation' to get a simulation with its committed projects
--added check for any committed projects on selected simulation
--added check for earliest committed project start year being less than the simulation analysis start
--added mongo db update for simulation status with message 'Error: Projects committed before analysis start' when earliest committed project start year is less than simulation analysis start
--throw constraint exception when earliest committed project start year is less than simulation analysis start
=> vnext/617: Prevent analysis if committed project start < analysis start

BridgeCareApp/VuejsApp/src/components/treatment-editor/TreatmentEditor.vue, BridgeCareApp/VuejsApp/src/components/treatment-editor/treatment-editor-dialogs/CreateTreatmentDialog.vue, BridgeCareApp/VuejsApp/src/components/treatment-editor/treatment-editor-tabs/FeasibilityTab.vue
-added boolean property to check if a treatment has been selected
-added a text input for the treatment name that acts similarly to the text input when a library is selected
-fixed bug where a created treatment was immediately selected after being created in the view
-added feasibility instantiation for new treatments
=> vnext/801: Input for Treatment Name Modification

BridgeCareApp/BridgeCare/BridgeCare.csproj, BridgeCareApp/BridgeCare/Controllers/AttributeController.cs, BridgeCareApp/BridgeCare/DataAccessLayer/AttributesDAL.cs, BridgeCareApp/BridgeCare/Interfaces/IAttributeRepo.cs, BridgeCareApp/BridgeCare/Models/AttributeSelectValuesResult.cs, BridgeCareApp/VuejsApp/src/services/attribute.service.ts, BridgeCareApp/VuejsApp/src/shared/components/CriteriaEditor.vue, BridgeCareApp/VuejsApp/src/shared/models/iAM/attribute.ts, BridgeCareApp/VuejsApp/src/shared/utils/http-utils.ts, BridgeCareApp/VuejsApp/src/store-modules/attribute.module.ts
-added API function 'GetAttributeSelectValues
-added DAL GetAttributeSelectValues
-added models: NetworkAttribute, AttributeSelectValues, AttributeSelectValuesResult
-updated getErrorMessage function to check for a 'statusText' property
-added action getATtributeSelectValues, mutator attributesSelectValuesMutator, and state property attributesSelectValues
-modified CriteriaEditor to check for new attributes on a change to the selectSubCriteriaClause, and if a new value is found to call the GetAttributeSelectValues API to update the list of values (if any) for the selected attribute in state
=> vnext/501: CriteriaEditor => dynamically generated dropdown lists for selected attributes

BridgeCareApp/VuejsApp/src/components/priority-editor/PriorityEditor.vue, BridgeCareApp/VuejsApp/src/components/priority-editor/priority-editor-dialogs/CreatePriorityDialog.vue
-removed validation requiring priority years to not be blank
-fixed textarea description for priority libraries being displayed even if there was a selected scenario (should only display when no scenario is selected)
=> vnext/837: Allow Blank Priority Year
