ARA-Trans/iAM

BridgeCareApp/VuejsApp/src/components/TopNavbar.vue

-added route link in TopNavbar to InvestmentEditor

Bug#91: Add InvestmentEditor Route to SideNav

---

BridgeCareApp/VuejsApp/src/shared/CriteriaEditor.vue

-added h3 header tag in around 'Criteria Editor' text
-added textarea to show current criteria output
-added setCurrentCriteriaOutput to set the currentCriteriaOutput property
-added @Watch on criteria property to update currentCriteriaOutput
-added setCurrentCriteriaOutput call in @Watch('stateCriteria')
-added style sections to replace inline styles

Feature #86 - CriteriaEditor Show Current Criteria Output

---

BridgeCareApp/VuejsApp/src/shared/dialogs/EquationEditor.vue

changed initial value for textareaInput from null to {} and set it as an HTMLTextAreaElement
-ran lint-fix

Bug/125: Equation Editor Null Property Fix

---

BridgeCareApp/BridgeCare/BridgeCare.csproj
BridgeCareApp/BridgeCare/Models/SummaryReport/ChartRowsModel.cs
BridgeCareApp/BridgeCare/Properties/Resources.Designer.cs
BridgeCareApp/BridgeCare/Properties/Resources.resx
BridgeCareApp/BridgeCare/Services/SummaryReport/BridgeRateDeckAreaWorkSummary.cs
BridgeCareApp/BridgeCare/Services/SummaryReport/ConditionBridgeCount.cs
BridgeCareApp/BridgeCare/Services/SummaryReport/ConditionDeckArea.cs
BridgeCareApp/BridgeCare/Services/SummaryReport/PoorBridgeCount.cs
BridgeCareApp/BridgeCare/Services/SummaryReport/PoorBridgeDeckArea.cs
BridgeCareApp/BridgeCare/Services/SummaryReport/StackedColumnChartCommon.cs
BridgeCareApp/BridgeCare/Services/SummaryReport/SummaryReportGenerator.cs

Poor Bridge Cnt, Poor Bridge DA reports implementation.
Common code handling.

5th, 6th reports are done.

---

BridgeCareApp/BridgeCare/App_Start/UnityConfig.cs
BridgeCareApp/BridgeCare/BridgeCare.csproj
BridgeCareApp/BridgeCare/DataAccessLayer/BridgeWorkSummaryData.cs
BridgeCareApp/BridgeCare/Interfaces/SummaryReport/IBridgeWorkSummaryData.cs
BridgeCareApp/BridgeCare/Interfaces/SummaryReport/ICommonSummaryReportData.cs
BridgeCareApp/BridgeCare/Services/SummaryReport/BridgeWorkSummary.cs
BridgeCareApp/BridgeCare/Services/SummaryReport/CostBudgetsWorkSummary.cs
BridgeCareApp/BridgeCare/Services/SummaryReport/SummaryReportGenerator.cs

- Budget section.
- Some quick refactoring.

Updated work summary report to show Total Budget yearly values from YEARLYINVESTMENTs.

---

BridgeCareApp/VuejsApp/src/components/investment-editor/InvestmentEditor.vue
BridgeCareApp/VuejsApp/src/components/investment-editor/investment-editor-dialogs/EditBudgetsDialog.vue

-corrected an incorrect filtering for previous budgets that didn't account the previous budget names
-removed uneccessary variable editedBudgetOrder

Bug/155: Investment Editor Edit Budgets Bug Fix

---

BridgeCareApp/VuejsApp/src/components/TopNavbar.vue
BridgeCareApp/VuejsApp/src/components/investment-editor/InvestmentEditor.vue
BridgeCareApp/VuejsApp/src/shared/dialogs/ReportsDownload.vue
BridgeCareApp/VuejsApp/src/store-modules/investment-editor.module.ts
BridgeCareApp/VuejsApp/src/store-modules/reports/reports.module.ts

Intentionally kept the commented out service calls because I ll use those to fetch the data from the Web API application

Feature/148 - Synced Investment Strategy (Library) data with the firebase db

---

BridgeCareApp/VuejsApp/src/components/scenarios/scenarios-dialogs/CommittedProjectsFileUploaderDialog.vue

-corrected import for math-utils.ts file

Bug 202: Fixed math-utils.ts import

---

BridgeCareApp/VuejsApp/src/components/scenarios/EditScenario.vue

-re-structured the html for a cleaner UI look

Feature/214: EditScenario Icons

---

BridgeCareApp/VuejsApp/src/components/investment-editor/InvestmentEditor.vue
BridgeCareApp/VuejsApp/src/store-modules/investment-editor.module.ts

-fixed issue where selected scenario id was not being applied to a selected investment library when applying an investment library to a scenario

Bug/255: InvestmentLibrary Selected Scenario Id fix

---

BridgeCareApp/VuejsApp/src/services/analysis-editor.service.ts
BridgeCareApp/VuejsApp/src/services/committed-projects.service.ts
BridgeCareApp/VuejsApp/src/services/equation-editor.service.ts
BridgeCareApp/VuejsApp/src/services/performance-editor.service.ts
BridgeCareApp/VuejsApp/src/services/treatment-editor.service.ts
BridgeCareApp/VuejsApp/src/shared/utils/axios-mock-adapter-instance.ts

-created a single instance of the axios mock adapter with a mock axios instance
-replaced all mock calls with the single instance of the mock adapter and mock axios instance

Bug/263: Axios Mock Adapter Fix

---

BridgeCareApp/BridgeCare/DataAccessLayer/TreatmentLibrary.cs
BridgeCareApp/VuejsApp/src/components/treatment-editor/treatment-editor-tabs/FeasibilityTab.vue
BridgeCareApp/VuejsApp/src/shared/models/iAM/treatment.ts
BridgeCareApp/VuejsApp/src/shared/utils/mock-data.ts

-instead of using null when a user deletes a feasibility on the feasibility, setting to empty feasibility
-set empty feasibility on a new treatment

Bug/267: Treatment Null Feasibility Fix

---

BridgeCareApp/VuejsApp/src/components/investment-editor/InvestmentEditor.vue
BridgeCareApp/VuejsApp/src/components/performance-editor/PerformanceEditor.vue
BridgeCareApp/VuejsApp/src/components/treatment-editor/TreatmentEditor.vue

-change the application of the selected scenario id from a .map to a .foreach

Bug/272: Library Editors .map to .foreach fix

---

BridgeCareApp/VuejsApp/src/shared/utils/mock-data.ts

…ervices became implemented, this was causing an issue with foreign key constraints with some of the data since certain data did not exist in the database

Bug/275: Fix FK Contraint Issues by Removing Bad Mock Data

---

BridgeCareApp/BridgeCare/BridgeCare.csproj
BridgeCareApp/BridgeCare/DataAccessLayer/Inventory/Inventory.cs
BridgeCareApp/BridgeCare/DataAccessLayer/Inventory/PennDotCrosswalk.cs
BridgeCareApp/BridgeCare/Models/Inventory/InventoryItemDetailModel.cs
BridgeCareApp/BridgeCare/Models/Inventory/InventoryItemModel.cs
BridgeCareApp/BridgeCare/Models/Inventory/InventoryModel.cs
BridgeCareApp/BridgeCare/Models/Inventory/InventoryNbiLoadRatingModel.cs
BridgeCareApp/BridgeCare/Models/Inventory/NbiLoadRating.cs
BridgeCareApp/BridgeCare/Services/InventoryItemDetailModelGenerator.cs
BridgeCareApp/VuejsApp/src/components/Inventory.vue
BridgeCareApp/VuejsApp/src/shared/models/iAM/inventory.ts
BridgeCareApp/VuejsApp/src/shared/utils/mock-data.ts

Inventory: NBI Load Rating section - UI and API side updates to fix/add/show data as per Excel template.

Inventory: NBI Load Rating section

---

BridgeCareApp/BridgeCare/DataAccessLayer/TreatmentLibrary.cs

the get was the bug not the update

Years before any and years before same are not updating from the database

---

BridgeCareApp/VuejsApp/src/components/performance-editor/PerformanceEditor.vue
BridgeCareApp/VuejsApp/src/components/treatment-editor/treatment-editor-tabs/ConsequencesTab.vue
BridgeCareApp/VuejsApp/src/components/treatment-editor/treatment-editor-tabs/CostsTab.vue
BridgeCareApp/VuejsApp/src/shared/modals/EquationEditorDialog.vue
BridgeCareApp/VuejsApp/src/shared/models/modals/equation-editor-dialog-data.ts

removed all references to isFunction property (excluding equation validation checking and equation submits)

Feature/308: Remove 'Is Function?' functionality from Equation Editor

---

BridgeCareApp/BridgeCare/Controllers/SectionLocatorController.cs
BridgeCareApp/BridgeCare/DataAccessLayer/SectionLocatorDAL.cs
BridgeCareApp/BridgeCare/Interfaces/ISectionLocator.cs

…ocationModel instead of an IQueryable of the model
-parameterized the raw sql of the SectionLocatorDAL.Locate function

Bug/348: SectionLocatorDAL Raw SQL Parameterization

---

BridgeCareApp/VuejsApp/VuejsApp.njsproj
BridgeCareApp/VuejsApp/src/components/investment-editor/InvestmentEditor.vue

The Tabs in their own components will be added later

added wireframe for criteria driven budget

---

BridgeCareApp/VuejsApp/src/App.vue

… will show when a nodejs call is made

Bug/383: Add Spinner for NodeJS

---

BridgeCareApp/BridgeCare/DataAccessLayer/Validation/Validation.cs
BridgeCareApp/VuejsApp/src/App.vue

-corrected bug that was building the where clause incorrectly 
-corrected bug that was returning an invalid result when no data is present

Bug/394: Criteria Editor Check Fix

---

BridgeCareApp/BridgeCare/BridgeCare.csproj
BridgeCareApp/BridgeCare/Controllers/TargetController.cs
BridgeCareApp/BridgeCare/DataAccessLayer/TargetsDAL.cs
BridgeCareApp/BridgeCare/EntityClasses/TargetsEntity.cs
BridgeCareApp/BridgeCare/Interfaces/ITarget.cs
BridgeCareApp/BridgeCare/Models/TargetLibraryModel.cs
BridgeCareApp/BridgeCare/Models/TargetModel.cs
BridgeCareApp/VuejsApp/src/components/remaining-life-limit-editor/RemainingLifeLimitEditor.vue
BridgeCareApp/VuejsApp/src/components/remaining-life-limit-editor/remaining-life-limit-editor-dialogs/CreateRemainingLifeLimitDialog.vue
BridgeCareApp/VuejsApp/src/components/remaining-life-limit-editor/remaining-life-limit-editor-dialogs/CreateRemainingLifeLimitLibraryDialog.vue
BridgeCareApp/VuejsApp/src/components/scenarios/EditScenario.vue
BridgeCareApp/VuejsApp/src/components/target-editor/TargetEditor.vue
BridgeCareApp/VuejsApp/src/services/target.service.ts
BridgeCareApp/VuejsApp/src/shared/models/iAM/target.ts
BridgeCareApp/VuejsApp/src/store-modules/priority.module.ts
BridgeCareApp/VuejsApp/src/store-modules/target.module.ts

-added a target library model for UI and API
-modified API GET & POST functions to match library functionality (future prep)
-modified UI module, actions, watchers with some library functionality code (future prep)
-fixed issue where saved targets were not being returned to the UI
-fixed linting errors

Bug/404: UI Receives Saved Targets Fix (with library functionality future prep)

---

BridgeCareApp/VuejsApp/src/App.vue
BridgeCareApp/VuejsApp/src/components/remaining-life-limit-editor/RemainingLifeLimitEditor.vue
BridgeCareApp/VuejsApp/src/components/remaining-life-limit-editor/remaining-life-limit-editor-dialogs/CreateRemainingLifeLimitDialog.vue
BridgeCareApp/VuejsApp/src/components/remaining-life-limit-editor/remaining-life-limit-editor-dialogs/CreateRemainingLifeLimitLibraryDialog.vue
BridgeCareApp/VuejsApp/src/components/scenarios/EditScenario.vue

-fixed linting errors
-fixed library side nav icon color
-fixed bug where attributes would not be populated in the select element on the CreateRemainingLifeLimitDialog

Bug/399: Attributes List Not Populating CreateRemainingLifeLimitDialog Select Element

---

BridgeCareApp/VuejsApp/src/components/scenarios/EditAnalysis.vue
BridgeCareApp/VuejsApp/src/store-modules/scenario.module.ts

-added actions and state for scenario analysis data
-replaced direct calls to AnalysisEditorService in EditAnalysis component with action dispatches
-removed navigation on 'Cancel' button click event

Bug/398: EditAnalysis 'Cancel' btn Fix

---

BridgeCareApp/VuejsApp/src/components/Inventory.vue
BridgeCareApp/VuejsApp/src/components/investment-editor/InvestmentEditor.vue

-added logic to set the matching bmsId when a brKey is selected and vice versa when a bmsId is selected the matching brKey is set
-fixed linting errors

Bug/390: Link BMS Id & BR Key Selection

---

BridgeCareApp/VuejsApp/src/assets/css/main.css
BridgeCareApp/VuejsApp/src/components/deficient-editor/DeficientEditor.vue
BridgeCareApp/VuejsApp/src/components/performance-editor/PerformanceEditor.vue
BridgeCareApp/VuejsApp/src/components/priority-editor/PriorityEditor.vue
BridgeCareApp/VuejsApp/src/components/remaining-life-limit-editor/RemainingLifeLimitEditor.vue
BridgeCareApp/VuejsApp/src/components/scenarios/EditAnalysis.vue
BridgeCareApp/VuejsApp/src/components/scenarios/Scenarios.vue
BridgeCareApp/VuejsApp/src/components/target-editor/TargetEditor.vue
BridgeCareApp/VuejsApp/src/components/treatment-editor/treatment-editor-tabs/ConsequencesTab.vue
BridgeCareApp/VuejsApp/src/components/treatment-editor/treatment-editor-tabs/CostsTab.vue
BridgeCareApp/VuejsApp/src/components/treatment-editor/treatment-editor-tabs/FeasibilityTab.vue
BridgeCareApp/VuejsApp/src/shared/modals/EditBudgetsDialog.vue

-changed all instances of the fa-edit icon to be green

470: Edit Icon Color Change

---

BridgeCareApp/VuejsApp/src/components/deficient-editor/DeficientEditor.vue
BridgeCareApp/VuejsApp/src/components/target-editor/TargetEditor.vue

I missed these two buttons when I was changing them all.

Change "Apply" to "Save" in target, deficient editors

---

BridgeCareApp/VuejsApp/src/App.vue
BridgeCareApp/VuejsApp/src/components/Authentication.vue

- Clear token refresh interval upon logging out
- Move logic that takes place when authentication changes from Authentication page to App.vue

vnext/543 - Prevent refresh attempts after logout

---

BridgeCareApp/BridgeCare/Security/Role.cs
BridgeCareApp/VuejsApp/src/App.vue
BridgeCareApp/VuejsApp/src/components/LandingPage.vue

Redirect browser to a penndot deployment logout page and back on logout.

vnext/522 - Fix logout for local builds and iam-deploy

---

BridgeCareApp/VuejsApp/src/App.vue

- Duplicated navigation no longer pollutes the DevTools console with promise rejection errors

vnext/580 - Prevent navigation duplication errors

---

BridgeCareApp/BridgeCare/DataAccessLayer/SummaryReport/BridgeDataDAL.cs
BridgeCareApp/VuejsApp/.env.production

- Blank ADTTOTAL is treated as less than 10,000 when generating reports

vnext/584 - Blank ADTTOTAL

---

BridgeCareApp/VuejsApp/src/shared/utils/mongo-model-conversion-utils.ts

- Prevent spread syntax ("...") from being used on non-object types, such as strings
- Make sure model conversion will work on all models

Vnext/590 - model conversion

---

BridgeCareApp/BridgeCare/packages.config

Fix #608: Add missing entries in BridgeCare packages.config.

---

iAM-legacy/Simulation/Simulation.cs

- Convert weighting string to lower case before comparisons

vnext/636 - Case-sensitivity of weighting

---

BridgeCareApp/VuejsApp/src/components/cash-flow-editor/CashFlowEditor.vue

-added currency formatting for cash flow split treatment limit amount

vnext/629: All Currency Fields Formatted as Currency

---

BridgeCareApp/VuejsApp/src/shared/modals/EquationEditorDialog.vue

-added missing flag logic to activate 'SAVE' button when an equation is validated

vnext/649: Equation UI 'SAVE' btn fix

---

BridgeCareApp/BridgeCare/DataAccessLayer/CommittedDAL.cs

When new commitments are submitted for a section, remove existing commitments for that section

vnext/658 - Overwrite old committed projects

---

BridgeCareApp/VuejsApp/src/components/user-criteria/UserCriteria.vue
BridgeCareApp/VuejsApp/src/shared/modals/EquationEditorDialog.vue

- Changed "Give Unrestricted Access" to "Allow All Assets"
- Moved a semicolon

vnext/665 - Security text change

---

BridgeCareApp/VuejsApp/src/shared/modals/EditBudgetsDialog.vue

- Prevent creation of non-unique budget names through the Vue app
- Prevent unwanted extra deletions when deleting budgets with non-unique names

vnext/679 - Enforce Unique Budget Names

---

BridgeCareApp/VuejsApp/src/App.vue
BridgeCareApp/VuejsApp/src/shared/modals/CriteriaEditorDialog.vue

-added bound getters for container in App.vue & CriteriaEditorDialog.vue
-added getters for CriteriaEditorDialog.vue layout and div elements for flexibility
-moved check buttons into main card container actions
-moved results messages to be inline with the check buttons

vnext/684: Keep Criteria Check Buttons in view on smaller resolutions

---

BridgeCareApp/VuejsApp/src/components/cash-flow-editor/CashFlowEditor.vue
BridgeCareApp/VuejsApp/src/components/deficient-editor/DeficientEditor.vue
BridgeCareApp/VuejsApp/src/components/investment-editor/InvestmentEditor.vue
BridgeCareApp/VuejsApp/src/components/performance-editor/PerformanceEditor.vue
BridgeCareApp/VuejsApp/src/components/priority-editor/PriorityEditor.vue
BridgeCareApp/VuejsApp/src/components/remaining-life-limit-editor/RemainingLifeLimitEditor.vue
BridgeCareApp/VuejsApp/src/components/target-editor/TargetEditor.vue
BridgeCareApp/VuejsApp/src/components/treatment-editor/TreatmentEditor.vue

-replaced all library de-select icons with caret-left

vnext/698: Replace library de-select 'X' icon with caret-left icon

---

BridgeCareApp/BridgeCareNodeApp/controllers/cashFlowLibraryController.js
BridgeCareApp/BridgeCareNodeApp/models/cashFlowLibraryModel.js
BridgeCareApp/BridgeCareNodeApp/routers/cashFlowLibraryRouter.js
BridgeCareApp/VuejsApp/src/components/cash-flow-editor/CashFlowEditor.vue
BridgeCareApp/VuejsApp/src/services/cash-flow.service.ts
BridgeCareApp/VuejsApp/src/shared/models/iAM/cash-flow.ts
BridgeCareApp/VuejsApp/src/store-modules/cash-flow.module.ts

- Add cash flow library deletion
- Add backend support for cash flow library ownership

vnext/692 - Cash Flow deletion

---

BridgeCareApp/BridgeCareNodeApp/authorization/authorizationFilter.js
BridgeCareApp/BridgeCareNodeApp/controllers/libraryAPIFunctions.js

- Modify Passport authorization middleware to return meaningful messages with 401 errors

vnext/666 - Node authorization messages

---

BridgeCareApp/BridgeCare/BridgeCare.csproj
BridgeCareApp/BridgeCare/DataAccessLayer/Validation/Validation.cs
BridgeCareApp/BridgeCare/Interfaces/IValidation.cs
BridgeCareApp/BridgeCare/Models/CriteriaValidationResult.cs
BridgeCareApp/VuejsApp/src/shared/modals/CriteriaEditorDialog.vue
BridgeCareApp/VuejsApp/src/shared/models/iAM/criteria.ts

-added a CriteriaValidationResult model replacing the return value of string with the model in the criteria validation API
-updated invalidation result messages to be bold and include a 0 results match as an invalidation
-added a notificaiton message to check the entire criteria output after validating a sub-criteria

vnext/685: Criteria Editor Message Updates

---

BridgeCareApp/BridgeCareNodeApp/controllers/libraryAPIFunctions.js
BridgeCareApp/BridgeCareNodeApp/models/cashFlowLibraryModel.js
BridgeCareApp/BridgeCareNodeApp/models/deficientLibraryModel.js
BridgeCareApp/BridgeCareNodeApp/models/investmentLibraryModel.js
BridgeCareApp/BridgeCareNodeApp/models/performanceLibraryModel.js
BridgeCareApp/BridgeCareNodeApp/models/priorityLibraryModel.js
BridgeCareApp/BridgeCareNodeApp/models/targetLibraryModel.js
BridgeCareApp/BridgeCareNodeApp/models/treatmentLibraryModel.js
BridgeCareApp/VuejsApp/src/components/cash-flow-editor/CashFlowEditor.vue
BridgeCareApp/VuejsApp/src/components/deficient-editor/DeficientEditor.vue
BridgeCareApp/VuejsApp/src/components/investment-editor/InvestmentEditor.vue
BridgeCareApp/VuejsApp/src/components/performance-editor/PerformanceEditor.vue
BridgeCareApp/VuejsApp/src/components/priority-editor/PriorityEditor.vue
BridgeCareApp/VuejsApp/src/components/target-editor/TargetEditor.vue
BridgeCareApp/VuejsApp/src/components/treatment-editor/TreatmentEditor.vue
BridgeCareApp/VuejsApp/src/shared/models/iAM/cash-flow.ts
BridgeCareApp/VuejsApp/src/shared/models/iAM/deficient.ts
BridgeCareApp/VuejsApp/src/shared/models/iAM/investment.ts
BridgeCareApp/VuejsApp/src/shared/models/iAM/performance.ts
BridgeCareApp/VuejsApp/src/shared/models/iAM/priority.ts
BridgeCareApp/VuejsApp/src/shared/models/iAM/target.ts
BridgeCareApp/VuejsApp/src/shared/models/iAM/treatment.ts
BridgeCareApp/VuejsApp/src/shared/utils/criteria-editor-parsers.ts

- Library owners (and administrators) can share libraries so that all users can modify them

Vnext/690 - Basic library sharing

---

BridgeCareApp/BridgeCare/Security/JWTParse.cs
BridgeCareApp/BridgeCare/Security/Role.cs
BridgeCareApp/BridgeCareNodeApp/authorization/authorizationFilter.js
BridgeCareApp/BridgeCareNodeApp/controllers/libraryAPIFunctions.js
BridgeCareApp/BridgeCareNodeApp/controllers/scenarioController.js
BridgeCareApp/VuejsApp/src/components/authentication/NoRole.vue
BridgeCareApp/VuejsApp/src/shared/utils/get-user-info.ts
BridgeCareApp/VuejsApp/src/shared/utils/parse-ldap.ts
BridgeCareApp/VuejsApp/src/store-modules/authentication.module.ts

- Handle users with multiple roles and with non-bams roles
- Add jbruner's email to the NoRole page

vnext/712 - Multiple (non-BAMS) roles

---

BridgeCareApp/VuejsApp/src/components/scenarios/Scenarios.vue

-updated simulation run alert message

vnext/695: Update Simulation Run Message

---

BridgeCareApp/BridgeCare/BridgeCare.csproj
BridgeCareApp/BridgeCare/Controllers/ValidationController.cs
BridgeCareApp/BridgeCare/DataAccessLayer/Validation/Validation.cs
BridgeCareApp/BridgeCare/Interfaces/IValidation.cs
BridgeCareApp/BridgeCare/Models/EquationValidationResult.cs
BridgeCareApp/VuejsApp/src/services/equation-editor.service.ts
BridgeCareApp/VuejsApp/src/shared/modals/EquationEditorDialog.vue
BridgeCareApp/VuejsApp/src/shared/models/iAM/equation-validation.ts
BridgeCareApp/VuejsApp/src/shared/models/iAM/equation.ts

-removed functionality for creating TIR data points separately from piecewise data points (all data points are piecewise, and all TIR data points come from converting piecewise data points into TIR data points)
-using same chart for both piecewise & TIR tabs
-added EquationValidationResult model and updated API/services to use this model when validating equations

vnext/671: Equation Editor Chart/Validation/TIR Updates/Fixes

---

BridgeCareApp/VuejsApp/src/components/cash-flow-editor/CashFlowEditor.vue

-updated UI buttons and column names based on the provided mock-up

vnext/686: Update Cash Flow Buttons & Column Names

---

BridgeCareApp/BridgeCare/BridgeCare.csproj
BridgeCareApp/BridgeCare/DataAccessLayer/CommittedDAL.cs
BridgeCareApp/BridgeCare/DataAccessLayer/SimulationDAL.cs
BridgeCareApp/BridgeCare/Services/CommittedProjects.cs
BridgeCareApp/BridgeCare/packages.config
iAM-legacy/Simulation/SimulationQueue.cs

- Uploading committed projects uses the simulation queue

Vnext/723 - Queuing for Committed Projects

---

BridgeCareApp/VuejsApp/src/shared/modals/EquationEditorDialog.vue
BridgeCareApp/VuejsApp/src/store-modules/scenario.module.ts

- Ensure that "Queued" status is set in mongodb before any other status updates can occur

vnext/738 - "Queued" race condition

---

Deployment/sql_scripts/treatment_budget_length.sql

- No app changes required
- Added database script to repo

vnext/743 - Error when saving long budget lists for treatments

---

BridgeCareApp/BridgeCare/Services/CommittedProjects.cs

- Set automatic No Treatment commitment consequences to +0 Change

vnext/754 - No Treatment commit consequences

---

BridgeCareApp/BridgeCare/Services/CommittedProjects.cs

Only add No Treatment for years where there is no treatment

vnext/754 - Committed Projects No Treatment

---

Deployment/deploy.ps1

- Script now automatically compresses deployments into .zip archives
- Output file structure changed to match Sharefile upload format
- iam-deploy deployment is now built first
- Timer no longer shows incorrect (negative) times

Deployment script tweaks

---

BridgeCareApp/BridgeCare/DataAccessLayer/SimulationDAL.cs
BridgeCareApp/BridgeCare/Models/SimulationModel.cs
BridgeCareApp/BridgeCareNodeApp/models/scenarioModel.js
BridgeCareApp/VuejsApp/src/components/scenarios/Scenarios.vue
BridgeCareApp/VuejsApp/src/shared/models/iAM/scenario.ts
BridgeCareApp/VuejsApp/src/store-modules/scenario.module.ts

-added 'lastRun' as a date property on the scenarios mongo db model
-added 'lastRun' as a nullable date property on the scenarios vue model
-added data table column for vue scenario's 'lastRun' property
-updated formatDate function to return null if an unformattedDate has no value
-added mongo db connection in SetSimulationLastRunDate API function to update the 'lastRun' property of the mongo db scenario object
-simplified code of various actions and mutators in the scenario.module file

vnext/782: Scenario 'Date Last Run' Column

---

iAM-legacy/Simulation/Simulation.cs

-fixed merge conflict in Simulation.cs for spanTotal

release v1.1.0 spanTotal fix

---

BridgeCareApp/VuejsApp/src/components/treatment-editor/TreatmentEditor.vue
BridgeCareApp/VuejsApp/src/components/treatment-editor/treatment-editor-tabs/ConsequencesTab.vue
BridgeCareApp/VuejsApp/src/shared/utils/input-validation-rules.ts

-added treatment rules for treatment consequences whereby blank change values are allowed only if there is an equation

vnext/838: Treatment.Consequences => Allow blank change if equation is present

---

BridgeCareApp/BridgeCare/BridgeCare.csproj
BridgeCareApp/BridgeCare/Controllers/AttributeController.cs
BridgeCareApp/BridgeCare/DataAccessLayer/AttributesDAL.cs
BridgeCareApp/BridgeCare/Interfaces/IAttributeRepo.cs
BridgeCareApp/BridgeCare/Models/AttributeSelectValuesResult.cs
BridgeCareApp/BridgeCare/Models/NetworkAttributes.cs
BridgeCareApp/VuejsApp/src/services/attribute.service.ts
BridgeCareApp/VuejsApp/src/shared/components/CriteriaEditor.vue
BridgeCareApp/VuejsApp/src/shared/models/iAM/attribute.ts
BridgeCareApp/VuejsApp/src/store-modules/attribute.module.ts

-changed http call type from GET to POST for GetAttributeSelectValues
-modified functionality for finding missing attributes to find all missing attributes for pre-existing criteria instead of singularly
-modified functionality for querying database for attribute values to use multiple queries for multiple attributes
-modifiedAttributeSelectValuesResult by adding an Attribute property
-modified error messages for attributes to output multiple messages if multiple attributes were sent to the API
-added NetworkAttributes model for use in sending multiple attributes to the API for querying

vnext/840: Criteria Editor UI Lock Fix
